global:
  scrape_interval: 5s  # Cada cuánto tiempo Prometheus recoge métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
